name: Smoke Tests (OpenJDK8)

on: [push]

jobs:
  others:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install -P smoke-tests --file pom.xml -fae
  windows:

    runs-on: windows-latest

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install -P smoke-tests --file pom.xml -fae

